services:
  payment-proxy-pao:
    build:
      context: ./payment-proxy
    hostname: payment-proxy-pao
    networks:
      - backend
    environment:
      - WATCH_FILES=${WATCH_FILES:-0}
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "200MB"

networks:
  backend:
    driver: bridge
